<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Seeder;

class CoursesSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            [
                'title' => 'Creative Writing Masterclass',
                'slug' => 'creative-writing-masterclass',
                'instructor' => 'Margaret Atwood',
                'description' => 'Learn the art of storytelling from one of the most celebrated authors of our time. This comprehensive course covers character development, plot structure, dialogue, and the revision process.',
                'syllabus' => json_encode([
                    'Week 1: Finding Your Voice',
                    'Week 2: Character Development',
                    'Week 3: Plot and Structure',
                    'Week 4: Dialogue and Scene Writing',
                    'Week 5: Setting and Atmosphere',
                    'Week 6: Revision and Editing',
                ]),
                'price' => 49.99,
                'duration_hours' => 24,
                'lessons_count' => 36,
                'level' => 'intermediate',
                'preview_video' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
                'documents' => json_encode([
                    ['title' => 'Writing Style Guide.pdf', 'size' => '2.4 MB', 'type' => 'pdf'],
                    ['title' => 'Character Development Worksheet.pdf', 'size' => '1.1 MB', 'type' => 'pdf'],
                    ['title' => 'Plot Structure Template.pdf', 'size' => '890 KB', 'type' => 'pdf'],
                ]),
                'quizzes' => json_encode([
                    [
                        'title' => 'Week 1-2: Voice & Character Quiz',
                        'questions' => [
                            ['q' => 'What is the most important element of finding your writing voice?', 'options' => ['Reading widely', 'Writing daily', 'Imitating others', 'Using complex words'], 'answer' => 1],
                            ['q' => 'Which technique best develops character depth?', 'options' => ['Physical description only', 'Backstory and motivation', 'Dialogue tags', 'Setting placement'], 'answer' => 1],
                            ['q' => 'Show don\'t tell means:', 'options' => ['Describe everything in detail', 'Use action and dialogue to reveal character', 'Never use adjectives', 'Avoid description entirely'], 'answer' => 1],
                        ],
                    ],
                    [
                        'title' => 'Week 3-4: Plot & Dialogue Quiz',
                        'questions' => [
                            ['q' => 'The three-act structure consists of:', 'options' => ['Beginning, middle, end', 'Setup, confrontation, resolution', 'Introduction, body, conclusion', 'Exposition, rising action, climax'], 'answer' => 1],
                            ['q' => 'Good dialogue should:', 'options' => ['Sound like real speech exactly', 'Reveal character and advance plot', 'Be as long as possible', 'Avoid conflict'], 'answer' => 1],
                            ['q' => 'A subplot serves to:', 'options' => ['Fill pages', 'Complicate the main story and add depth', 'Confuse the reader', 'Replace the main plot'], 'answer' => 1],
                        ],
                    ],
                ]),
                'is_featured' => true,
                'is_active' => true,
                'category' => 'writing',
            ],
            [
                'title' => 'English Literature: Shakespeare to Modernism',
                'slug' => 'english-literature-shakespeare-modernism',
                'instructor' => 'Prof. Harold Bloom',
                'description' => 'A comprehensive journey through English literature from the Elizabethan era to the modernist movement. Analyze key texts, historical contexts, and literary criticism.',
                'syllabus' => json_encode([
                    'Module 1: Shakespearean Tragedies',
                    'Module 2: Romantic Poetry',
                    'Module 3: Victorian Novel',
                    'Module 4: Modernist Experimentation',
                    'Module 5: Post-Colonial Voices',
                ]),
                'price' => 39.99,
                'duration_hours' => 30,
                'lessons_count' => 45,
                'level' => 'advanced',
                'preview_video' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
                'documents' => json_encode([
                    ['title' => 'Shakespeare Complete Works - Reading List.pdf', 'size' => '3.2 MB', 'type' => 'pdf'],
                    ['title' => 'Literary Criticism Handbook.pdf', 'size' => '1.8 MB', 'type' => 'pdf'],
                    ['title' => 'Timeline of English Literature.pdf', 'size' => '650 KB', 'type' => 'pdf'],
                    ['title' => 'Essay Writing Guide for Literature.pdf', 'size' => '1.2 MB', 'type' => 'pdf'],
                ]),
                'quizzes' => json_encode([
                    [
                        'title' => 'Module 1-2: Shakespeare & Romanticism Quiz',
                        'questions' => [
                            ['q' => 'Hamlet is primarily concerned with:', 'options' => ['Love and romance', 'Revenge and moral uncertainty', 'Political power', 'Religious devotion'], 'answer' => 1],
                            ['q' => 'Romantic poetry emphasized:', 'options' => ['Reason and logic', 'Emotion, nature, and individualism', 'Industrial progress', 'Classical forms'], 'answer' => 1],
                            ['q' => 'Wordsworth is best known for:', 'options' => ['Satirical plays', 'Lyrical Ballads and nature poetry', 'Historical novels', 'Political essays'], 'answer' => 1],
                        ],
                    ],
                    [
                        'title' => 'Module 3-5: Victorian to Post-Colonial Quiz',
                        'questions' => [
                            ['q' => 'The Victorian novel is characterized by:', 'options' => ['Stream of consciousness', 'Social realism and moral concern', 'Minimalist prose', 'Fantasy elements'], 'answer' => 1],
                            ['q' => 'Modernist literature often features:', 'options' => ['Linear narrative', 'Fragmented structure and interior monologue', 'Happy endings', 'Omniscient narration'], 'answer' => 1],
                            ['q' => 'Post-colonial literature primarily addresses:', 'options' => ['Medieval themes', 'Identity, power, and cultural displacement', 'Scientific progress', 'Aristocratic life'], 'answer' => 1],
                        ],
                    ],
                ]),
                'is_featured' => true,
                'is_active' => true,
                'category' => 'literature',
            ],
            [
                'title' => 'IELTS Preparation: Band 7+ Strategy',
                'slug' => 'ielts-preparation-band-7',
                'instructor' => 'Dr. Sarah Thompson',
                'description' => 'Master all four sections of the IELTS exam with proven strategies, practice tests, and personalized feedback. Achieve your target band score with expert guidance.',
                'syllabus' => json_encode([
                    'Section 1: Listening Skills & Practice',
                    'Section 2: Reading Comprehension Techniques',
                    'Section 3: Writing Task 1 & 2',
                    'Section 4: Speaking Fluency & Confidence',
                    'Section 5: Full Mock Exams',
                ]),
                'price' => 59.99,
                'duration_hours' => 40,
                'lessons_count' => 52,
                'level' => 'intermediate',
                'preview_video' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
                'documents' => json_encode([
                    ['title' => 'IELTS Band Descriptors.pdf', 'size' => '1.5 MB', 'type' => 'pdf'],
                    ['title' => 'Writing Task 1 Templates.pdf', 'size' => '2.1 MB', 'type' => 'pdf'],
                    ['title' => 'Speaking Practice Questions.pdf', 'size' => '980 KB', 'type' => 'pdf'],
                    ['title' => 'Vocabulary Builder - Academic Words.pdf', 'size' => '3.4 MB', 'type' => 'pdf'],
                    ['title' => 'Full Practice Test 1.pdf', 'size' => '4.2 MB', 'type' => 'pdf'],
                ]),
                'quizzes' => json_encode([
                    [
                        'title' => 'Listening & Reading Practice Quiz',
                        'questions' => [
                            ['q' => 'In IELTS Listening Section 1, you typically hear:', 'options' => ['An academic lecture', 'A conversation between two people in a social context', 'A group discussion', 'A monologue'], 'answer' => 1],
                            ['q' => 'The best strategy for IELTS Reading True/False/Not Given is:', 'options' => ['Guess if unsure', 'Find exact paraphrases in the text', 'Answer based on your knowledge', 'Look for keywords only'], 'answer' => 1],
                            ['q' => 'How many minutes are recommended for IELTS Reading Passage 1?', 'options' => ['10 minutes', '15 minutes', '20 minutes', '25 minutes'], 'answer' => 2],
                        ],
                    ],
                    [
                        'title' => 'Writing & Speaking Practice Quiz',
                        'questions' => [
                            ['q' => 'IELTS Writing Task 2 should be at least:', 'options' => ['150 words', '200 words', '250 words', '300 words'], 'answer' => 2],
                            ['q' => 'In the Speaking test, fluency refers to:', 'options' => ['Using complex vocabulary', 'Speaking at a natural pace without excessive hesitation', 'Having a native accent', 'Speaking as fast as possible'], 'answer' => 1],
                            ['q' => 'For a Band 7+ in Writing, you must:', 'options' => ['Use only simple sentences', 'Present a clear position throughout with relevant examples', 'Write exactly 300 words', 'Avoid personal opinions'], 'answer' => 1],
                        ],
                    ],
                ]),
                'is_featured' => true,
                'is_active' => true,
                'category' => 'language',
            ],
            [
                'title' => 'Business English for Professionals',
                'slug' => 'business-english-professionals',
                'instructor' => 'James Mitchell',
                'description' => 'Elevate your professional communication with targeted business English training. Cover emails, presentations, negotiations, and networking in English.',
                'syllabus' => json_encode([
                    'Unit 1: Professional Email Writing',
                    'Unit 2: Meeting & Presentation Skills',
                    'Unit 3: Negotiation Language',
                    'Unit 4: Networking & Small Talk',
                    'Unit 5: Report Writing',
                ]),
                'price' => 34.99,
                'duration_hours' => 18,
                'lessons_count' => 28,
                'level' => 'beginner',
                'documents' => json_encode([
                    ['title' => 'Business Email Templates.pdf', 'size' => '1.3 MB', 'type' => 'pdf'],
                    ['title' => 'Presentation Phrase Bank.pdf', 'size' => '780 KB', 'type' => 'pdf'],
                    ['title' => 'Negotiation Vocabulary Guide.pdf', 'size' => '1.1 MB', 'type' => 'pdf'],
                ]),
                'quizzes' => json_encode([
                    [
                        'title' => 'Email & Meeting Skills Quiz',
                        'questions' => [
                            ['q' => 'The most appropriate opening for a formal business email is:', 'options' => ['Hey there!', 'Dear Mr. Smith,', 'Hi buddy,', 'What\'s up?'], 'answer' => 1],
                            ['q' => 'In a business meeting, "Let\'s move on to the next item" is an example of:', 'options' => ['Interrupting', 'Transitioning', 'Concluding', 'Disagreeing'], 'answer' => 1],
                            ['q' => 'Which phrase is most appropriate for disagreeing politely?', 'options' => ['You\'re wrong', 'I see your point, but I have a different view', 'That makes no sense', 'I don\'t agree at all'], 'answer' => 1],
                        ],
                    ],
                ]),
                'is_featured' => false,
                'is_active' => true,
                'category' => 'language',
            ],
            [
                'title' => 'Grammar Essentials: From Basics to Mastery',
                'slug' => 'grammar-essentials',
                'instructor' => 'Prof. Emma Richardson',
                'description' => 'Build a rock-solid foundation in English grammar. From parts of speech to complex sentence structures, this course covers everything you need for confident writing.',
                'syllabus' => json_encode([
                    'Chapter 1: Parts of Speech',
                    'Chapter 2: Sentence Structure',
                    'Chapter 3: Tenses & Aspects',
                    'Chapter 4: Punctuation Mastery',
                    'Chapter 5: Common Errors & How to Avoid Them',
                ]),
                'price' => 24.99,
                'duration_hours' => 15,
                'lessons_count' => 22,
                'level' => 'beginner',
                'documents' => json_encode([
                    ['title' => 'Grammar Quick Reference Chart.pdf', 'size' => '950 KB', 'type' => 'pdf'],
                    ['title' => 'Tense Usage Guide.pdf', 'size' => '1.4 MB', 'type' => 'pdf'],
                    ['title' => 'Punctuation Rules Handbook.pdf', 'size' => '720 KB', 'type' => 'pdf'],
                ]),
                'quizzes' => json_encode([
                    [
                        'title' => 'Parts of Speech & Sentence Structure Quiz',
                        'questions' => [
                            ['q' => 'In the sentence "She runs quickly," the word "quickly" is a:', 'options' => ['Noun', 'Verb', 'Adjective', 'Adverb'], 'answer' => 3],
                            ['q' => 'A compound sentence contains:', 'options' => ['One independent clause', 'Two or more independent clauses joined by a conjunction', 'Only dependent clauses', 'No verbs'], 'answer' => 1],
                            ['q' => 'Which is a preposition?', 'options' => ['Run', 'Beautiful', 'Under', 'Quickly'], 'answer' => 2],
                        ],
                    ],
                    [
                        'title' => 'Tenses & Punctuation Quiz',
                        'questions' => [
                            ['q' => '"I have been studying for three hours" uses which tense?', 'options' => ['Present perfect', 'Past continuous', 'Present perfect continuous', 'Past perfect'], 'answer' => 2],
                            ['q' => 'Which sentence uses the semicolon correctly?', 'options' => ['I went to the store; and bought milk.', 'She loves reading; he prefers movies.', 'The cat; sat on the mat.', 'Running; is fun.'], 'answer' => 1],
                            ['q' => '"Their going to the park" is incorrect because:', 'options' => ['Their should be They\'re', 'Their should be There', 'The verb is wrong', 'It should be "They going"'], 'answer' => 0],
                        ],
                    ],
                ]),
                'is_featured' => false,
                'is_active' => true,
                'category' => 'language',
            ],
            [
                'title' => 'Academic Writing & Research Methods',
                'slug' => 'academic-writing-research',
                'instructor' => 'Dr. Robert Chen',
                'description' => 'Learn to write compelling academic papers, conduct thorough research, and cite sources correctly. Essential for university students and researchers.',
                'syllabus' => json_encode([
                    'Module 1: Research Design & Methodology',
                    'Module 2: Literature Review Techniques',
                    'Module 3: Academic Essay Structure',
                    'Module 4: Citation Styles (APA, MLA, Chicago)',
                    'Module 5: Thesis Writing',
                ]),
                'price' => 44.99,
                'duration_hours' => 28,
                'lessons_count' => 40,
                'level' => 'advanced',
                'preview_video' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
                'documents' => json_encode([
                    ['title' => 'APA 7th Edition Citation Guide.pdf', 'size' => '2.8 MB', 'type' => 'pdf'],
                    ['title' => 'Research Paper Template.docx', 'size' => '450 KB', 'type' => 'docx'],
                    ['title' => 'Literature Review Checklist.pdf', 'size' => '680 KB', 'type' => 'pdf'],
                    ['title' => 'Thesis Structure Outline.pdf', 'size' => '1.1 MB', 'type' => 'pdf'],
                ]),
                'quizzes' => json_encode([
                    [
                        'title' => 'Research Methods & Literature Review Quiz',
                        'questions' => [
                            ['q' => 'A literature review should:', 'options' => ['List every source you found', 'Synthesize and critically analyze existing research', 'Only include recent sources', 'Be purely descriptive'], 'answer' => 1],
                            ['q' => 'Qualitative research methods include:', 'options' => ['Statistical analysis', 'Surveys with large samples', 'Interviews and case studies', 'Experiments with control groups'], 'answer' => 2],
                            ['q' => 'A hypothesis is:', 'options' => ['A proven fact', 'A testable prediction', 'A research question', 'A conclusion'], 'answer' => 1],
                        ],
                    ],
                    [
                        'title' => 'Citation & Thesis Writing Quiz',
                        'questions' => [
                            ['q' => 'In APA style, in-text citations include:', 'options' => ['Author and year', 'Author, year, and page number for direct quotes', 'Full bibliographic details', 'Footnotes only'], 'answer' => 1],
                            ['q' => 'Plagiarism can be avoided by:', 'options' => ['Changing a few words', 'Properly paraphrasing and citing sources', 'Using someone else\'s ideas without credit', 'Only citing direct quotes'], 'answer' => 1],
                            ['q' => 'The thesis statement should appear:', 'options' => ['At the end of the paper', 'In the introduction, typically at the end', 'Only in the abstract', 'Nowhere - it should be implied'], 'answer' => 1],
                        ],
                    ],
                ]),
                'is_featured' => true,
                'is_active' => true,
                'category' => 'writing',
            ],
            [
                'title' => 'Conversational English: Speak with Confidence',
                'slug' => 'conversational-english',
                'instructor' => 'Lisa Parker',
                'description' => 'Practice real-world English conversations for everyday situations. Build fluency, improve pronunciation, and gain confidence in speaking.',
                'syllabus' => json_encode([
                    'Week 1: Daily Conversations',
                    'Week 2: Travel & Hospitality',
                    'Week 3: Social Events & Gatherings',
                    'Week 4: Expressing Opinions & Debates',
                    'Week 5: Idioms & Slang',
                ]),
                'price' => 29.99,
                'duration_hours' => 20,
                'lessons_count' => 30,
                'level' => 'beginner',
                'documents' => json_encode([
                    ['title' => 'Essential Conversation Phrases.pdf', 'size' => '1.2 MB', 'type' => 'pdf'],
                    ['title' => 'Idioms & Expressions Dictionary.pdf', 'size' => '2.5 MB', 'type' => 'pdf'],
                    ['title' => 'Pronunciation Guide.pdf', 'size' => '890 KB', 'type' => 'pdf'],
                ]),
                'quizzes' => json_encode([
                    [
                        'title' => 'Daily Conversations & Travel Quiz',
                        'questions' => [
                            ['q' => 'The most natural response to "How are you?" is:', 'options' => ['I am existing adequately', 'I\'m good, thanks! How about you?', 'My physical condition is satisfactory', 'I function well'], 'answer' => 1],
                            ['q' => 'At a hotel, you would say:', 'options' => ['I want sleep place', 'I\'d like to check in, please', 'Give me room key', 'Sleep here now'], 'answer' => 1],
                            ['q' => '"Could you recommend a good restaurant?" is an example of:', 'options' => ['A command', 'A polite request', 'A statement', 'An exclamation'], 'answer' => 1],
                        ],
                    ],
                ]),
                'is_featured' => false,
                'is_active' => true,
                'category' => 'language',
            ],
            [
                'title' => 'Publishing Your First Book: A Complete Guide',
                'slug' => 'publishing-first-book',
                'instructor' => 'Amanda Clarke',
                'description' => 'From manuscript to marketplace — learn the entire publishing process including editing, cover design, marketing, and distribution for both traditional and self-publishing.',
                'syllabus' => json_encode([
                    'Phase 1: Manuscript Preparation',
                    'Phase 2: Editing & Proofreading',
                    'Phase 3: Cover Design & Formatting',
                    'Phase 4: Publishing Options',
                    'Phase 5: Marketing & Launch Strategy',
                ]),
                'price' => 54.99,
                'duration_hours' => 22,
                'lessons_count' => 34,
                'level' => 'intermediate',
                'documents' => json_encode([
                    ['title' => 'Manuscript Formatting Guide.pdf', 'size' => '1.6 MB', 'type' => 'pdf'],
                    ['title' => 'Book Proposal Template.docx', 'size' => '380 KB', 'type' => 'docx'],
                    ['title' => 'Publishing Contracts Explained.pdf', 'size' => '2.1 MB', 'type' => 'pdf'],
                    ['title' => 'Marketing Checklist for Authors.pdf', 'size' => '750 KB', 'type' => 'pdf'],
                ]),
                'quizzes' => json_encode([
                    [
                        'title' => 'Manuscript & Editing Quiz',
                        'questions' => [
                            ['q' => 'A standard manuscript format uses:', 'options' => ['Any font you prefer', '12pt Times New Roman, double-spaced', 'Comic Sans for readability', 'Single spacing to save pages'], 'answer' => 1],
                            ['q' => 'Developmental editing focuses on:', 'options' => ['Spelling and grammar', 'Story structure, pacing, and character arcs', 'Cover design', 'Marketing strategy'], 'answer' => 1],
                            ['q' => 'Beta readers are:', 'options' => ['Professional editors', 'Early readers who provide feedback', 'Book reviewers', 'Publishing agents'], 'answer' => 1],
                        ],
                    ],
                    [
                        'title' => 'Publishing & Marketing Quiz',
                        'questions' => [
                            ['q' => 'An ISBN is:', 'options' => ['A copyright registration', 'A unique identifier for books', 'A publishing contract', 'A marketing tool'], 'answer' => 1],
                            ['q' => 'Self-publishing advantages include:', 'options' => ['Guaranteed bookstore placement', 'Higher royalties and creative control', 'Free editing services', 'Automatic bestseller status'], 'answer' => 1],
                            ['q' => 'The most effective book launch strategy includes:', 'options' => ['Posting once on social media', 'Building an email list and advance reader team', 'Waiting for organic discovery', 'Only relying on Amazon ads'], 'answer' => 1],
                        ],
                    ],
                ]),
                'is_featured' => false,
                'is_active' => true,
                'category' => 'writing',
            ],
            [
                'id' => 9,
                'category_id' => 1,
                'title' => 'Advanced English Grammar',
                'slug' => 'advanced-english-grammar',
                'instructor' => 'Michael Brown',
                'description' => 'Master English grammar rules.',
                'price' => 49.99,
                'duration_hours' => 12,
                'level' => 'Intermediate',
                'status' => 'published',
                'image' => 'courses/grammar.jpg',
                'preview_video' => 'https://www.youtube.com/embed/2z7f5Xz7v0I',
                'is_featured' => false,
                'is_active' => true,
                'category' => 'language',
            ],
            [
                'id' => 10,
                'category_id' => 1,
                'title' => 'Creative Storytelling',
                'slug' => 'creative-storytelling',
                'instructor' => 'Emma Watson',
                'description' => 'Learn storytelling techniques.',
                'price' => 39.99,
                'duration_hours' => 8,
                'level' => 'Beginner',
                'status' => 'published',
                'image' => 'courses/story.jpg',
                'preview_video' => 'https://www.youtube.com/embed/Nj-hdQMa3uA',
                'is_featured' => false,
                'is_active' => true,
                'category' => 'writing',
            ],
            [
                'id' => 11,
                'category_id' => 2,
                'title' => 'Quantum Physics Basics',
                'slug' => 'quantum-physics-basics',
                'instructor' => 'Dr. Brian Cox',
                'description' => 'Intro to quantum world.',
                'price' => 59.99,
                'duration_hours' => 10,
                'level' => 'Beginner',
                'status' => 'published',
                'image' => 'courses/quantum.jpg',
                'preview_video' => 'https://www.youtube.com/embed/p7bzE1E5PMY',
                'is_featured' => false,
                'is_active' => true,
                'category' => 'science',
            ],
            [
                'id' => 12,
                'category_id' => 2,
                'title' => 'Space Science & Astronomy',
                'slug' => 'space-science-astronomy',
                'instructor' => 'Neil Tyson',
                'description' => 'Explore the universe.',
                'price' => 44.99,
                'duration_hours' => 9,
                'level' => 'Beginner',
                'status' => 'published',
                'image' => 'courses/space.jpg',
                'preview_video' => 'https://www.youtube.com/embed/X9otDixAtFw',
                'is_featured' => false,
                'is_active' => true,
                'category' => 'science',
            ],
            [
                'id' => 13,
                'category_id' => 3,
                'title' => 'Java DSA Bootcamp',
                'slug' => 'java-dsa-bootcamp',
                'instructor' => 'Sarah Lee',
                'description' => 'Data structures using Java.',
                'price' => 79.99,
                'duration_hours' => 18,
                'level' => 'Advanced',
                'status' => 'published',
                'image' => 'courses/dsa.jpg',
                'preview_video' => 'https://www.youtube.com/embed/8hly31xKli0',
                'is_featured' => false,
                'is_active' => true,
                'category' => 'technology',
            ],
            [
                'id' => 14,
                'category_id' => 3,
                'title' => 'Full Stack Development',
                'slug' => 'full-stack-development',
                'instructor' => 'Alex Morgan',
                'description' => 'Frontend + backend complete.',
                'price' => 89.99,
                'duration_hours' => 20,
                'level' => 'Intermediate',
                'status' => 'published',
                'image' => 'courses/fullstack.jpg',
                'preview_video' => 'https://www.youtube.com/embed/nu_pCVPKzTk',
                'is_featured' => false,
                'is_active' => true,
                'category' => 'technology',
            ],
        ];

        foreach ($courses as $course) {
            Course::updateOrCreate(['slug' => $course['slug']], $course);
        }
    }
}
