<?php

namespace Database\Seeders;

use App\Models\Book;
use App\Models\Category;
use App\Models\User;
use App\Models\Review;
use App\Models\Question;
use App\Models\Course;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        User::updateOrCreate(
            ['email' => 'admin@luminabooks.com'],
            [
                'name' => 'Admin User',
                'password' => Hash::make('admin123'),
                'role' => 'staff',
                'phone' => '+1234567890',
            ]
        );

        User::updateOrCreate(
            ['email' => 'john@example.com'],
            [
                'name' => 'John Doe',
                'password' => Hash::make('password123'),
                'role' => 'customer',
                'phone' => '+1987654321',
                'address' => '123 Main St, New York, NY',
            ]
        );

        $categories = [
            ['name' => 'Fiction', 'slug' => 'fiction', 'description' => 'Fictional novels and stories'],
            ['name' => 'Science', 'slug' => 'science', 'description' => 'Scientific books and research'],
            ['name' => 'Technology', 'slug' => 'technology', 'description' => 'Programming and tech books'],
            ['name' => 'History', 'slug' => 'history', 'description' => 'Historical accounts and analysis'],
            ['name' => 'Business', 'slug' => 'business', 'description' => 'Business and entrepreneurship'],
            ['name' => 'Self-Help', 'slug' => 'self-help', 'description' => 'Personal development books'],
        ];

        foreach ($categories as $cat) {
            Category::updateOrCreate(['slug' => $cat['slug']], $cat);
        }

        $catId = [];
        foreach ($categories as $cat) {
            $catId[$cat['slug']] = Category::where('slug', $cat['slug'])->value('id');
        }

        $books = [
            [
                'category_id' => $catId['fiction'],
                'title' => 'The Great Gatsby',
                'author' => 'F. Scott Fitzgerald',
                'description' => 'A story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.',
                'price' => 12.99,
                'stock' => 50,
                'isbn' => '978-0743273565',
                'publisher' => 'Scribner',
                'pages' => 180,
                'is_featured' => true,
                'pdf_price' => 8.99,
                'pdf_path' => 'pdfs/gatsby.pdf',
            ],
            [
                'category_id' => $catId['fiction'],
                'title' => 'To Kill a Mockingbird',
                'author' => 'Harper Lee',
                'description' => 'The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it.',
                'price' => 14.99,
                'stock' => 45,
                'isbn' => '978-0061120084',
                'publisher' => 'Harper Perennial',
                'pages' => 336,
                'is_featured' => true,
                'pdf_price' => 9.99,
                'pdf_path' => 'pdfs/mockingbird.pdf',
            ],
            [
                'category_id' => $catId['fiction'],
                'title' => '1984',
                'author' => 'George Orwell',
                'description' => 'A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism.',
                'price' => 11.99,
                'stock' => 60,
                'isbn' => '978-0451524935',
                'publisher' => 'Signet Classic',
                'pages' => 328,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['science'],
                'title' => 'A Brief History of Time',
                'author' => 'Stephen Hawking',
                'description' => 'An exploration of cosmology and the nature of the universe.',
                'price' => 18.99,
                'stock' => 30,
                'isbn' => '978-0553380163',
                'publisher' => 'Bantam',
                'pages' => 212,
                'is_featured' => true,
                'pdf_price' => 9.99,
                'pdf_path' => 'pdfs/hawking-time.pdf',
            ],
            [
                'category_id' => $catId['science'],
                'title' => 'The Selfish Gene',
                'author' => 'Richard Dawkins',
                'description' => 'A groundbreaking work on evolutionary biology and genetics.',
                'price' => 16.99,
                'stock' => 25,
                'isbn' => '978-0198788607',
                'publisher' => 'Oxford University Press',
                'pages' => 360,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['technology'],
                'title' => 'Clean Code',
                'author' => 'Robert C. Martin',
                'description' => 'A handbook of agile software craftsmanship for writing clean, maintainable code.',
                'price' => 39.99,
                'stock' => 40,
                'isbn' => '978-0132350884',
                'publisher' => 'Prentice Hall',
                'pages' => 464,
                'is_featured' => true,
                'pdf_price' => 24.99,
                'pdf_path' => 'pdfs/clean-code.pdf',
            ],
            [
                'category_id' => $catId['technology'],
                'title' => 'Design Patterns',
                'author' => 'Gang of Four',
                'description' => 'Elements of reusable object-oriented software design patterns.',
                'price' => 44.99,
                'stock' => 20,
                'isbn' => '978-0201633610',
                'publisher' => 'Addison-Wesley',
                'pages' => 395,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['technology'],
                'title' => 'The Pragmatic Programmer',
                'author' => 'David Thomas & Andrew Hunt',
                'description' => 'Your journey to mastery in software development.',
                'price' => 42.99,
                'stock' => 35,
                'isbn' => '978-0135957059',
                'publisher' => 'Addison-Wesley',
                'pages' => 352,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['history'],
                'title' => 'Sapiens: A Brief History of Humankind',
                'author' => 'Yuval Noah Harari',
                'description' => 'A groundbreaking narrative of humanity\'s creation and evolution.',
                'price' => 22.99,
                'stock' => 55,
                'isbn' => '978-0062316097',
                'publisher' => 'Harper',
                'pages' => 464,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['history'],
                'title' => 'Guns, Germs, and Steel',
                'author' => 'Jared Diamond',
                'description' => 'The fates of human societies and why history unfolded as it did.',
                'price' => 19.99,
                'stock' => 28,
                'isbn' => '978-0393354324',
                'publisher' => 'W. W. Norton',
                'pages' => 528,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['business'],
                'title' => 'Atomic Habits',
                'author' => 'James Clear',
                'description' => 'An easy and proven way to build good habits and break bad ones.',
                'price' => 16.99,
                'stock' => 70,
                'isbn' => '978-0735211292',
                'publisher' => 'Avery',
                'pages' => 320,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['business'],
                'title' => 'The Lean Startup',
                'author' => 'Eric Ries',
                'description' => 'How today\'s entrepreneurs use continuous innovation to create radically successful businesses.',
                'price' => 17.99,
                'stock' => 32,
                'isbn' => '978-0307887894',
                'publisher' => 'Crown Business',
                'pages' => 336,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['self-help'],
                'title' => 'Thinking, Fast and Slow',
                'author' => 'Daniel Kahneman',
                'description' => 'A groundbreaking tour of the mind and the two systems that drive the way we think.',
                'price' => 15.99,
                'stock' => 42,
                'isbn' => '978-0374533557',
                'publisher' => 'Farrar, Straus and Giroux',
                'pages' => 499,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['self-help'],
                'title' => 'The Power of Now',
                'author' => 'Eckhart Tolle',
                'description' => 'A guide to spiritual enlightenment and living in the present moment.',
                'price' => 13.99,
                'stock' => 38,
                'isbn' => '978-1577314806',
                'publisher' => 'New World Library',
                'pages' => 236,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['fiction'],
                'title' => 'The Alchemist',
                'author' => 'Paulo Coelho',
                'description' => 'A magical story about following your dreams and listening to your heart.',
                'price' => 14.99,
                'stock' => 65,
                'isbn' => '978-0062315007',
                'publisher' => 'HarperOne',
                'pages' => 208,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['science'],
                'title' => 'Cosmos',
                'author' => 'Carl Sagan',
                'description' => 'A personal voyage through the universe and our place in it.',
                'price' => 20.99,
                'stock' => 22,
                'isbn' => '978-0345539434',
                'publisher' => 'Ballantine Books',
                'pages' => 432,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['fiction'],
                'title' => 'The Catcher in the Rye',
                'author' => 'J.D. Salinger',
                'description' => 'A teenage boy\'s account of his experiences in New York City after being expelled from prep school.',
                'price' => 13.99,
                'stock' => 48,
                'isbn' => '978-0316769174',
                'publisher' => 'Little, Brown',
                'pages' => 277,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['fiction'],
                'title' => 'Pride and Prejudice',
                'author' => 'Jane Austen',
                'description' => 'A romantic novel of manners and marriage among the landed gentry of Georgian England.',
                'price' => 11.99,
                'stock' => 55,
                'isbn' => '978-0141439518',
                'publisher' => 'Penguin Classics',
                'pages' => 432,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['fiction'],
                'title' => 'Wuthering Heights',
                'author' => 'Emily Brontë',
                'description' => 'A tale of love and revenge amid the Yorkshire moors, spanning two generations.',
                'price' => 12.99,
                'stock' => 35,
                'isbn' => '978-0141439556',
                'publisher' => 'Penguin Classics',
                'pages' => 352,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['fiction'],
                'title' => 'The Hobbit',
                'author' => 'J.R.R. Tolkien',
                'description' => 'A fantasy adventure of a reluctant hobbit hero embarking on an unexpected quest.',
                'price' => 15.99,
                'stock' => 62,
                'isbn' => '978-0547928227',
                'publisher' => 'Houghton Mifflin Harcourt',
                'pages' => 310,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['fiction'],
                'title' => 'The Lord of the Rings',
                'author' => 'J.R.R. Tolkien',
                'description' => 'An epic fantasy journey through Middle-earth to destroy an ancient evil ring.',
                'price' => 29.99,
                'stock' => 58,
                'isbn' => '978-0544003415',
                'publisher' => 'Houghton Mifflin Harcourt',
                'pages' => 1178,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['fiction'],
                'title' => 'Jane Eyre',
                'author' => 'Charlotte Brontë',
                'description' => 'A gothic romance about a poor orphan girl and her relationship with a mysterious man.',
                'price' => 12.99,
                'stock' => 42,
                'isbn' => '978-0141441146',
                'publisher' => 'Penguin Classics',
                'pages' => 477,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['fiction'],
                'title' => 'Moby Dick',
                'author' => 'Herman Melville',
                'description' => 'An epic adventure about a captain\'s obsessive hunt for a white whale.',
                'price' => 16.99,
                'stock' => 28,
                'isbn' => '978-0142437247',
                'publisher' => 'Penguin Classics',
                'pages' => 736,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['fiction'],
                'title' => 'The Count of Monte Cristo',
                'author' => 'Alexandre Dumas',
                'description' => 'A tale of adventure and revenge about an unjustly imprisoned man and his escape and transformation.',
                'price' => 17.99,
                'stock' => 51,
                'isbn' => '978-0140449266',
                'publisher' => 'Penguin Classics',
                'pages' => 928,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['science'],
                'title' => 'The God Delusion',
                'author' => 'Richard Dawkins',
                'description' => 'A rational examination of religious faith and the case for atheism.',
                'price' => 17.99,
                'stock' => 33,
                'isbn' => '978-0618680009',
                'publisher' => 'Houghton Mifflin',
                'pages' => 406,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['science'],
                'title' => 'A Brief History of Nearly Everything',
                'author' => 'Bill Bryson',
                'description' => 'A hilarious and fascinating journey through natural history and scientific discovery.',
                'price' => 18.99,
                'stock' => 44,
                'isbn' => '978-0767908185',
                'publisher' => 'Broadway',
                'pages' => 544,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['science'],
                'title' => 'The Magic of Reality',
                'author' => 'Richard Dawkins',
                'description' => 'A beautifully illustrated exploration of the science behind apparently magical phenomena.',
                'price' => 25.99,
                'stock' => 26,
                'isbn' => '978-1451675023',
                'publisher' => 'Free Press',
                'pages' => 272,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['technology'],
                'title' => 'Python Cookbook',
                'author' => 'David Beazley & Brian K. Jones',
                'description' => 'Recipes and solutions for common Python programming tasks.',
                'price' => 36.99,
                'stock' => 37,
                'isbn' => '978-1449357337',
                'publisher' => 'O\'Reilly',
                'pages' => 704,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['technology'],
                'title' => 'JavaScript: The Good Parts',
                'author' => 'Douglas Crockford',
                'description' => 'A comprehensive guide to the best programming practices in JavaScript.',
                'price' => 29.99,
                'stock' => 41,
                'isbn' => '978-0596517748',
                'publisher' => 'O\'Reilly',
                'pages' => 176,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['technology'],
                'title' => 'Structure and Interpretation of Computer Programs',
                'author' => 'Hal Abelson, Jerry Sussman, Julie Sussman',
                'description' => 'A legendary MIT textbook on computer programming fundamentals.',
                'price' => 68.99,
                'stock' => 15,
                'isbn' => '978-0262510875',
                'publisher' => 'MIT Press',
                'pages' => 688,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['technology'],
                'title' => 'The C Programming Language',
                'author' => 'Brian W. Kernighan & Dennis M. Ritchie',
                'description' => 'The definitive guide to C programming from two of its creators.',
                'price' => 34.99,
                'stock' => 29,
                'isbn' => '978-0131103627',
                'publisher' => 'Prentice Hall',
                'pages' => 274,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['technology'],
                'title' => 'Code: The Hidden Language of Computer Hardware and Software',
                'author' => 'Charles Petzold',
                'description' => 'An exploration of the history and principles that underlie all digital technology.',
                'price' => 24.99,
                'stock' => 39,
                'isbn' => '978-0735611313',
                'publisher' => 'Prentice Hall',
                'pages' => 400,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['technology'],
                'title' => 'Refactoring: Improving the Design of Existing Code',
                'author' => 'Martin Fowler',
                'description' => 'Techniques for restructuring code to improve its design without changing behavior.',
                'price' => 51.99,
                'stock' => 22,
                'isbn' => '978-0201485677',
                'publisher' => 'Addison-Wesley',
                'pages' => 464,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['history'],
                'title' => 'The Silk Road: Connecting Cultures and Commerce',
                'author' => 'Peter Frankopan',
                'description' => 'A fascinating exploration of the trade routes that shaped world history.',
                'price' => 21.99,
                'stock' => 34,
                'isbn' => '978-0374246326',
                'publisher' => 'Farrar, Straus and Giroux',
                'pages' => 448,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['history'],
                'title' => 'The Fall of the Roman Empire',
                'author' => 'Christopher Kelly',
                'description' => 'A gripping account of Rome\'s transformation and the barbarian invasions.',
                'price' => 19.99,
                'stock' => 30,
                'isbn' => '978-0393327588',
                'publisher' => 'W. W. Norton',
                'pages' => 432,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['history'],
                'title' => 'The American Civil War: A Military History',
                'author' => 'John Keegan',
                'description' => 'A comprehensive military analysis of America\'s bloodiest conflict.',
                'price' => 24.99,
                'stock' => 27,
                'isbn' => '978-0394746739',
                'publisher' => 'Knopf',
                'pages' => 536,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['history'],
                'title' => 'Empires of the Atlantic World',
                'author' => 'David Cannadine',
                'description' => 'A comparative history of the British and American imperial experiences.',
                'price' => 23.99,
                'stock' => 31,
                'isbn' => '978-0300107173',
                'publisher' => 'Yale University Press',
                'pages' => 640,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['business'],
                'title' => 'Good to Great',
                'author' => 'Jim Collins',
                'description' => 'Why some companies make the leap and other don\'t - and how to transform your business.',
                'price' => 27.99,
                'stock' => 45,
                'isbn' => '978-0066620992',
                'publisher' => 'HarperBusiness',
                'pages' => 320,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['business'],
                'title' => 'The Innovators',
                'author' => 'Walter Isaacson',
                'description' => 'How a group of hackers, geniuses, and geeks created the digital revolution.',
                'price' => 19.99,
                'stock' => 38,
                'isbn' => '978-1476708690',
                'publisher' => 'Simon & Schuster',
                'pages' => 656,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['business'],
                'title' => 'Zero to One',
                'author' => 'Peter Thiel & Blake Masters',
                'description' => 'Notes on startups, or how to build the future - lessons from the PayPal founder.',
                'price' => 16.99,
                'stock' => 52,
                'isbn' => '978-0804139298',
                'publisher' => 'Crown Business',
                'pages' => 224,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['business'],
                'title' => 'Crushing It!',
                'author' => 'Gary Vaynerchuk',
                'description' => 'How to leverage social media to build your personal brand and business.',
                'price' => 17.99,
                'stock' => 43,
                'isbn' => '978-0061914516',
                'publisher' => 'HarperStudio',
                'pages' => 272,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['business'],
                'title' => 'The Art of the Deal',
                'author' => 'Donald Trump & Tony Schwartz',
                'description' => 'Behind-the-scenes stories and strategies from a legendary dealmaker.',
                'price' => 16.99,
                'stock' => 25,
                'isbn' => '978-0345409041',
                'publisher' => 'Ballantine',
                'pages' => 355,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['self-help'],
                'title' => 'Mindset: The New Psychology of Success',
                'author' => 'Carol S. Dweck',
                'description' => 'How a simple change of mindset can improve your success in business and life.',
                'price' => 17.99,
                'stock' => 67,
                'isbn' => '978-0345472328',
                'publisher' => 'Ballantine',
                'pages' => 288,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['self-help'],
                'title' => 'The 7 Habits of Highly Effective People',
                'author' => 'Stephen Covey',
                'description' => 'Principles for personal transformation and achieving your goals.',
                'price' => 18.99,
                'stock' => 59,
                'isbn' => '978-1451639619',
                'publisher' => 'Free Press',
                'pages' => 432,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['self-help'],
                'title' => 'Man\'s Search for Meaning',
                'author' => 'Viktor Frankl',
                'description' => 'A Holocaust survivor\'s reflections on meaning, freedom, and human resilience.',
                'price' => 15.99,
                'stock' => 53,
                'isbn' => '978-0807014271',
                'publisher' => 'Beacon Press',
                'pages' => 165,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['self-help'],
                'title' => 'Flow: The Psychology of Optimal Experience',
                'author' => 'Mihaly Csikszentmihalyi',
                'description' => 'The science of happiness and how to achieve deep engagement in work and life.',
                'price' => 17.99,
                'stock' => 36,
                'isbn' => '978-0061339202',
                'publisher' => 'Harper Perennial',
                'pages' => 464,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['self-help'],
                'title' => 'The Four Agreements',
                'author' => 'Don Miguel Ruiz',
                'description' => 'A practical guide to personal freedom and fulfillment through ancient wisdom.',
                'price' => 14.99,
                'stock' => 61,
                'isbn' => '978-1878424310',
                'publisher' => 'Amber-Allen Publishing',
                'pages' => 160,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['fiction'],
                'title' => 'The Odyssey',
                'author' => 'Homer',
                'description' => 'An ancient Greek epic about a hero\'s long journey home after the Trojan War.',
                'price' => 13.99,
                'stock' => 32,
                'isbn' => '978-0143039952',
                'publisher' => 'Penguin Classics',
                'pages' => 448,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['fiction'],
                'title' => 'Frankenstein',
                'author' => 'Mary Shelley',
                'description' => 'A Gothic horror novel about a scientist and his monstrous creation.',
                'price' => 11.99,
                'stock' => 40,
                'isbn' => '978-0486282114',
                'publisher' => 'Dover',
                'pages' => 288,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['fiction'],
                'title' => 'Dracula',
                'author' => 'Bram Stoker',
                'description' => 'A classic Gothic vampire novel told through letters, diary entries, and newspaper clippings.',
                'price' => 12.99,
                'stock' => 38,
                'isbn' => '978-0486411095',
                'publisher' => 'Dover',
                'pages' => 432,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['fiction'],
                'title' => 'The Strange Case of Dr Jekyll and Mr Hyde',
                'author' => 'Robert Louis Stevenson',
                'description' => 'A novella about a doctor\'s descent into madness through a dual personality.',
                'price' => 9.99,
                'stock' => 50,
                'isbn' => '978-0486264685',
                'publisher' => 'Dover',
                'pages' => 80,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['fiction'],
                'title' => 'The Picture of Dorian Gray',
                'author' => 'Oscar Wilde',
                'description' => 'A novel about vanity and corruption featuring a man whose portrait ages instead of him.',
                'price' => 10.99,
                'stock' => 46,
                'isbn' => '978-0486274867',
                'publisher' => 'Dover',
                'pages' => 128,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['science'],
                'title' => 'The Right Stuff',
                'author' => 'Tom Wolfe',
                'description' => 'The epic story of American test pilots and the early space program.',
                'price' => 18.99,
                'stock' => 29,
                'isbn' => '978-0374248573',
                'publisher' => 'Farrar, Straus and Giroux',
                'pages' => 464,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['science'],
                'title' => 'Pale Blue Dot',
                'author' => 'Carl Sagan',
                'description' => 'A meditation on human existence and our place in the universe.',
                'price' => 17.99,
                'stock' => 33,
                'isbn' => '978-0345376596',
                'publisher' => 'Ballantine',
                'pages' => 384,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['technology'],
                'title' => 'Introduction to Algorithms',
                'author' => 'Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein',
                'description' => 'The definitive comprehensive textbook on computer algorithms and data structures.',
                'price' => 89.99,
                'stock' => 18,
                'isbn' => '978-0262033848',
                'publisher' => 'MIT Press',
                'pages' => 1312,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['technology'],
                'title' => 'Domain-Driven Design',
                'author' => 'Eric Evans',
                'description' => 'A guide to tackling complexity in software architecture through domain-driven design.',
                'price' => 54.99,
                'stock' => 20,
                'isbn' => '978-0321125675',
                'publisher' => 'Addison-Wesley',
                'pages' => 560,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['technology'],
                'title' => 'Test Driven Development',
                'author' => 'Kent Beck',
                'description' => 'By Example - a practical guide to writing better code through testing.',
                'price' => 44.99,
                'stock' => 24,
                'isbn' => '978-0321146533',
                'publisher' => 'Addison-Wesley',
                'pages' => 240,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['history'],
                'title' => 'The French Revolution',
                'author' => 'Thomas Carlyle',
                'description' => 'A vivid narrative history of one of history\'s most transformative events.',
                'price' => 22.99,
                'stock' => 26,
                'isbn' => '978-0486424569',
                'publisher' => 'Dover',
                'pages' => 720,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['history'],
                'title' => 'Napoleon: A Life',
                'author' => 'Andrew Roberts',
                'description' => 'A comprehensive biography of the French military leader and emperor.',
                'price' => 25.99,
                'stock' => 35,
                'isbn' => '978-0393247602',
                'publisher' => 'W. W. Norton',
                'pages' => 926,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['business'],
                'title' => 'Venture Capitalists at War',
                'author' => 'Dan Senor & Saul Singer',
                'description' => 'The story of Israeli entrepreneurs and their impact on global innovation.',
                'price' => 20.99,
                'stock' => 28,
                'isbn' => '978-0446556286',
                'publisher' => 'Twelve',
                'pages' => 400,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['business'],
                'title' => 'The Startup Way',
                'author' => 'Eric Ries',
                'description' => 'How modern companies use entrepreneurial management to transform culture and drive growth.',
                'price' => 18.99,
                'stock' => 41,
                'isbn' => '978-0385539578',
                'publisher' => 'Crown Business',
                'pages' => 336,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['self-help'],
                'title' => 'Emotional Intelligence',
                'author' => 'Daniel Goleman',
                'description' => 'Why it can matter more than IQ - a groundbreaking exploration of emotions and success.',
                'price' => 17.99,
                'stock' => 54,
                'isbn' => '978-0553375305',
                'publisher' => 'Bantam',
                'pages' => 368,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['self-help'],
                'title' => 'Radical Acceptance',
                'author' => 'Tara Brach',
                'description' => 'Embracing your life with the heart of a Buddha - finding peace through acceptance.',
                'price' => 17.99,
                'stock' => 32,
                'isbn' => '978-0553380163',
                'publisher' => 'Bantam',
                'pages' => 336,
                'is_featured' => false,
            ],
            [
                'category_id' => $catId['fiction'],
                'title' => 'The Name of the Wind',
                'author' => 'Patrick Rothfuss',
                'description' => 'The first book in an epic fantasy series about a legendary figure retelling his past.',
                'price' => 18.99,
                'stock' => 56,
                'isbn' => '978-0756404741',
                'publisher' => 'DAW Books',
                'pages' => 662,
                'is_featured' => true,
            ],
            [
                'category_id' => $catId['fiction'],
                'title' => 'American Gods',
                'author' => 'Neil Gaiman',
                'description' => 'A dark fantasy mixing mythology with modern America in an epic road trip narrative.',
                'price' => 17.99,
                'stock' => 47,
                'isbn' => '978-0380789023',
                'publisher' => 'William Morrow',
                'pages' => 635,
                'is_featured' => true,
            ],
        ];

        foreach ($books as $book) {
            Book::updateOrCreate(['title' => $book['title']], $book);
        }

        // Map book titles to IDs for reviews and questions
        $bookTitleToId = Book::pluck('id', 'title')->toArray();

        $reviewers = [
            ['name' => 'Sarah Mitchell', 'email' => 'sarah@email.com'],
            ['name' => 'James Wilson', 'email' => 'james@email.com'],
            ['name' => 'Emily Chen', 'email' => 'emily@email.com'],
            ['name' => 'Michael Brown', 'email' => 'michael@email.com'],
            ['name' => 'Lisa Anderson', 'email' => 'lisa@email.com'],
            ['name' => 'David Kim', 'email' => 'david@email.com'],
            ['name' => 'Rachel Green', 'email' => 'rachel@email.com'],
            ['name' => 'Tom Harris', 'email' => 'tom@email.com'],
            ['name' => 'Anna Lee', 'email' => 'anna@email.com'],
            ['name' => 'Chris Taylor', 'email' => 'chris@taylor.com'],
        ];

        $reviews = [
            ['book_title' => 'The Great Gatsby', 'rating' => 5, 'comment' => 'An absolute masterpiece! Fitzgerald\'s prose is breathtaking and the portrayal of the Jazz Age is unmatched. Every re-read reveals new layers of meaning.'],
            ['book_title' => 'The Great Gatsby', 'rating' => 4, 'comment' => 'Beautiful writing but the characters are so flawed it\'s hard to root for anyone. Still, a must-read classic that everyone should experience.'],
            ['book_title' => 'The Great Gatsby', 'rating' => 5, 'comment' => 'The symbolism in this book is incredible. The green light, the eyes of Dr. T.J. Eckleburg - every detail has meaning. A true work of art.'],
            ['book_title' => 'To Kill a Mockingbird', 'rating' => 5, 'comment' => 'This book changed my perspective on justice and morality. Scout\'s innocent yet perceptive narration makes the heavy themes accessible and deeply moving.'],
            ['book_title' => 'To Kill a Mockingbird', 'rating' => 5, 'comment' => 'Atticus Finch is one of the greatest literary heroes ever created. His quiet courage and moral integrity are inspiring. A timeless classic.'],
            ['book_title' => '1984', 'rating' => 4, 'comment' => 'Orwell\'s dystopian vision feels more relevant than ever. The concepts of doublethink and Newspeak are chillingly prescient. A must-read for our times.'],
            ['book_title' => '1984', 'rating' => 5, 'comment' => 'Terrifyingly accurate prediction of surveillance culture. Big Brother is watching indeed. This book should be required reading in every school.'],
            ['book_title' => 'A Brief History of Time', 'rating' => 5, 'comment' => 'Stephen Hawking makes the most complex concepts of the universe accessible to everyone. I\'ve read it three times and each time I understand more.'],
            ['book_title' => 'A Brief History of Time', 'rating' => 4, 'comment' => 'Some parts are challenging to grasp but the overall journey through cosmology is fascinating. Hawking\'s passion for the subject shines through every page.'],
            ['book_title' => 'The Selfish Gene', 'rating' => 4, 'comment' => 'Dawkins presents a compelling case for gene-centered evolution. It challenges how we think about life and natural selection. Dense but rewarding.'],
            ['book_title' => 'Clean Code', 'rating' => 5, 'comment' => 'Every programmer should read this book. Uncle Bob\'s principles have transformed how I write code. Clean code is not just a goal, it\'s a discipline.'],
            ['book_title' => 'Clean Code', 'rating' => 4, 'comment' => 'Excellent practical advice for writing maintainable code. Some examples feel dated but the core principles are timeless. A developer\'s essential guide.'],
            ['book_title' => 'Design Patterns', 'rating' => 4, 'comment' => 'The Gang of Four patterns are foundational to software design. Some patterns feel over-engineered for modern development, but understanding them is invaluable.'],
            ['book_title' => 'The Pragmatic Programmer', 'rating' => 5, 'comment' => 'This book made me a better developer overnight. The pragmatic approach to software engineering is refreshing and immediately applicable to any project.'],
            ['book_title' => 'Sapiens: A Brief History of Humankind', 'rating' => 5, 'comment' => 'Harari weaves anthropology, history, and philosophy into an incredible narrative. It fundamentally changed how I think about human civilization and progress.'],
            ['book_title' => 'Sapiens: A Brief History of Humankind', 'rating' => 4, 'comment' => 'Fascinating journey through human history. Some arguments are debatable but the overall thesis is thought-provoking and well-researched.'],
            ['book_title' => 'Guns, Germs, and Steel', 'rating' => 4, 'comment' => 'Diamond\'s thesis about geography shaping civilization is compelling. A sweeping analysis that connects dots across continents and millennia.'],
            ['book_title' => 'Atomic Habits', 'rating' => 5, 'comment' => 'Atomic Habits is the best self-help book I\'ve ever read. Clear\'s four-step framework is simple yet powerful. I\'ve already seen real changes in my daily routine.'],
            ['book_title' => 'Atomic Habits', 'rating' => 5, 'comment' => 'Finally, a habits book that actually works! The concept of 1% improvement is transformative. Small changes really do compound into remarkable results.'],
            ['book_title' => 'The Lean Startup', 'rating' => 4, 'comment' => 'Great framework for startups. The build-measure-learn loop is a game-changer. Some concepts are overused now but the original insights are still valuable.'],
            ['book_title' => 'Thinking, Fast and Slow', 'rating' => 5, 'comment' => 'Kahneman\'s exploration of System 1 and System 2 thinking is mind-blowing. It explains so many of our irrational decisions. Essential reading for anyone.'],
            ['book_title' => 'Thinking, Fast and Slow', 'rating' => 4, 'comment' => 'Dense but incredibly insightful. The research on cognitive biases is eye-opening. Be prepared to question your own thinking after reading this.'],
            ['book_title' => 'The Power of Now', 'rating' => 5, 'comment' => 'Tolle\'s message about living in the present moment is simple yet profound. This book helped me find peace in the chaos of modern life.'],
            ['book_title' => 'The Power of Now', 'rating' => 4, 'comment' => 'A spiritual guide that actually makes sense. The concept of the "pain body" resonated deeply with me. Practical wisdom for everyday mindfulness.'],
            ['book_title' => 'The Alchemist', 'rating' => 5, 'comment' => 'A beautiful fable about following your dreams. Coelho\'s writing is poetic and the story is universal. I return to this book every few years.'],
            ['book_title' => 'The Alchemist', 'rating' => 4, 'comment' => 'Simple yet profound. The Alchemist reminds us that the journey is as important as the destination. A quick read with lasting impact.'],
            ['book_title' => 'Cosmos', 'rating' => 5, 'comment' => 'Carl Sagan\'s wonder at the cosmos is infectious. This book reignited my childhood fascination with space and the universe. Beautifully written and illustrated.'],
            ['book_title' => 'Cosmos', 'rating' => 4, 'comment' => 'Sagan makes astronomy and cosmology accessible to everyone. His poetic prose combined with scientific rigor creates something truly special.'],
        ];

        foreach ($reviews as $i => $review) {
            $reviewer = $reviewers[$i % count($reviewers)];
            $bookId = $bookTitleToId[$review['book_title']] ?? null;
            if (!$bookId) continue;
            Review::create([
                'book_id' => $bookId,
                'user_id' => null,
                'user_name' => $reviewer['name'],
                'user_email' => $reviewer['email'],
                'rating' => $review['rating'],
                'comment' => $review['comment'],
                'is_approved' => true,
                'created_at' => now()->subDays(rand(1, 90)),
            ]);
        }

        $questions = [
            ['book_title' => 'The Great Gatsby', 'question' => 'Is this the original unabridged version or a shortened edition? I want the complete text.', 'answer' => 'This is the complete, unabridged version of The Great Gatsby as originally published by Scribner.'],
            ['book_title' => 'The Great Gatsby', 'question' => 'Does this edition include any study guides or annotations?', 'answer' => 'This is the standard edition without additional study materials. Check our "Annotated Classics" section for editions with guides.'],
            ['book_title' => 'To Kill a Mockingbird', 'question' => 'Is this appropriate for a 13-year-old reader?', 'answer' => 'Yes, it\'s commonly assigned in middle school curricula. Some themes are mature but handled thoughtfully.'],
            ['book_title' => 'To Kill a Mockingbird', 'question' => 'How does this compare to the movie adaptation?', 'answer' => 'The book offers much deeper character development and internal monologue that the films can\'t capture. Always read the book first!'],
            ['book_title' => '1984', 'question' => 'Which edition/translation is this? Some versions have different appendices.', 'answer' => 'This is the standard Signet Classic edition which includes the original text. It does not include additional essays or appendices.'],
            ['book_title' => 'Clean Code', 'question' => 'Is this the 2nd edition? I heard it has updated examples.', 'answer' => 'This is the original edition. The 2nd edition is available separately with updated code examples in modern languages.'],
            ['book_title' => 'Clean Code', 'question' => 'Are the code examples in Java or can they be applied to other languages?', 'answer' => 'The examples are primarily in Java but the principles are language-agnostic and apply to any object-oriented language.'],
            ['book_title' => 'Sapiens: A Brief History of Humankind', 'question' => 'How does this compare to "Guns, Germs, and Steel" by the same author?', 'answer' => 'Sapiens covers the entire span of human history while GGS focuses on why certain civilizations dominated. They complement each other well.'],
            ['book_title' => 'Atomic Habits', 'question' => 'Does this book include worksheets or practical exercises?', 'answer' => 'Yes! The book includes practical exercises at the end of each chapter plus access to free downloadable worksheets on the author\'s website.'],
            ['book_title' => 'The Alchemist', 'question' => 'Is this the illustrated edition or text only?', 'answer' => 'This is the standard text-only edition. The illustrated edition with artwork by Pablo Picasso is available separately.'],
        ];

        foreach ($questions as $i => $q) {
            $asker = $reviewers[$i % count($reviewers)];
            $bookId = $bookTitleToId[$q['book_title']] ?? null;
            if (!$bookId) continue;
            Question::create([
                'book_id' => $bookId,
                'user_id' => null,
                'user_name' => $asker['name'],
                'user_email' => $asker['email'],
                'question' => $q['question'],
                'answer' => $q['answer'],
                'is_answered' => !empty($q['answer']),
                'is_approved' => true,
                'created_at' => now()->subDays(rand(1, 60)),
            ]);
        }

        // Seed books
        $this->call(\Database\Seeders\BooksSeeder::class);

        // Seed courses
        $this->call(\Database\Seeders\CoursesSeeder::class);

        // Seed orders after creating users and books
        $this->call(\Database\Seeders\OrdersSeeder::class);
    }
}
